[package]
name = "notebackend_python"
version = "0.1.0"
authors = ["Jun Wu <quark@lihdd.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.13"
cpython = "0.5"
notebackend_types = { path = "../notebackend_types" }
