[package]
name = "notebackend"
version = "0.1.0"
authors = ["Jun Wu <quark@lihdd.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bitflags = "1"
dirs = "3"
fs2 = "0.4"
libloading = "0.6"
once_cell = "1"
parking_lot = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tempfile = "3"
notebackend_types = { path = "../notebackend_types" }

[dev-dependencies]
drawdag = { package = "esl01-drawdag", version = "0.1" }