name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest ]
        lazarus-versions: [ 2.0.10 ]

    steps:
    - uses: actions/checkout@v2
    - name: Rust Information
      run: rustup show
    - name: Build backend
      run: cargo build --manifest-path backend/Cargo.toml --verbose --target-dir=target
    - name: Run backend tests
      run: cargo test --manifest-path backend/Cargo.toml --verbose --target-dir=target
    - name: Copy build assets (Linux)
      if: runner.os == 'Linux'
      run: cp target/debug/libnotebackend.so frontend
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.8
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
    - name: Build GUI
      run: lazbuild "frontend/foonote.lpi"
