name: gui

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        lazarus-versions: [2.0.10]
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.6
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
    - name: Build the Main Application
      run: lazbuild "frontend/foonote.lpi"
