on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build backend
      run: cargo build --release --manifest-path backend/Cargo.toml --verbose --target-dir=target
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.8
      with:
        lazarus-version: 2.0.10
    - name: Build GUI
      run: lazbuild --build-mode=Release "frontend/foonote.lpi"
    - name: Build Scintilla
      run: |
        cd thirdparty\scintilla\win32
        nmake -f scintilla.mak
    - name: Copy Binaries
      run: |
        mkdir dist
        cp target/release/notebackend.dll dist
        cp target/release/notebackend_python.dll dist
        cp frontend/foonote.exe dist
        cp thirdparty/scintilla/bin/scintilla.dll dist
        $compress = @{
          Path = "dist\*"
          CompressionLevel = "Optimal"
          DestinationPath = "FooNote-Win64.zip"
        }
        Compress-Archive @compress
        Get-FileHash -Algorithm SHA256 "FooNote-Win64.zip" | tee SHA256.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          FooNote-Win64.zip
          SHA256.txt
        prerelease: ${{ endsWith(github.ref, 'beta') }}
